/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#474647",
        "secondary": "#7c5800",
        "outline-variant": "#c7c6ca",
        "surface-subtle": "#F8FAFC",
        "surface-tint": "#5f5e5f",
        "on-secondary": "#ffffff",
        "surface-container": "#e6eeff",
        "on-tertiary": "#ffffff",
        "status-error": "#EF4444",
        "error-container": "#ffdad6",
        "primary": "#000000",
        "outline": "#76777b",
        "inverse-on-surface": "#ebf1ff",
        "surface-container-low": "#eff3ff",
        "status-warning": "#F59E0B",
        "on-tertiary-fixed-variant": "#484644",
        "on-secondary-fixed": "#271900",
        "status-success": "#10B981",
        "tertiary": "#000000",
        "inverse-surface": "#263141",
        "secondary-fixed-dim": "#febb24",
        "primary-container": "#1b1b1c",
        "on-primary": "#ffffff",
        "tertiary-container": "#1c1b19",
        "on-primary-container": "#858384",
        "background": "#f8f9ff",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#1c1b19",
        "surface": "#f8f9ff",
        "on-surface": "#111c2b",
        "tertiary-fixed-dim": "#cac6c2",
        "primary-fixed": "#e5e2e3",
        "on-tertiary-container": "#868380",
        "on-error": "#ffffff",
        "inverse-primary": "#c8c6c7",
        "tertiary-fixed": "#e6e2de",
        "border-light": "#E2E8F0",
        "surface-dim": "#cfdbef",
        "secondary-fixed": "#ffdea7",
        "surface-variant": "#d8e3f8",
        "surface-container-high": "#dee9fe",
        "secondary-container": "#febb24",
        "primary-fixed-dim": "#c8c6c7",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#d8e3f8",
        "on-primary-fixed": "#1b1b1c",
        "error": "#ba1a1a",
        "on-secondary-container": "#6d4d00",
        "on-background": "#111c2b",
        "on-secondary-fixed-variant": "#5e4200",
        "on-surface-variant": "#46474a",
        "surface-bright": "#f8f9ff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "unit": "4px",
        "gutter": "16px",
        "max-width": "1440px",
        "margin-desktop": "32px",
        "margin-mobile": "16px"
      },
      maxWidth: {
        "dashboard": "1440px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Outfit", "sans-serif"],
        "body-md": ["Outfit", "sans-serif"],
        "headline-lg": ["Outfit", "sans-serif"],
        "headline-md": ["Outfit", "sans-serif"],
        "display-lg": ["Outfit", "sans-serif"],
        "label-md": ["Outfit", "sans-serif"],
        "data-tabular": ["Outfit", "sans-serif"],
        "title-lg": ["Outfit", "sans-serif"],
        "body-lg": ["Outfit", "sans-serif"]
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "0", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "0", "fontWeight": "700" }],
        "label-md": ["12px", { "lineHeight": "16px", "fontWeight": "600" }],
        "data-tabular": ["13px", { "lineHeight": "18px", "fontWeight": "500" }],
        "title-lg": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
