export const getKycList = () => [
  {
    id: 1,
    name: 'Apex Distributors Ltd.',
    type: 'Distributor',
    submitted: 'Oct 24, 2023',
    status: 'Pending',
    idNumber: 'KYC-2023-8942',
    bizType: 'B2B Distributor',
    region: 'North America',
    pan: 'ABCDE1234F',
    registration: '1234 5678 9012',
    notes: '',
    files: [
      { name: 'Bank_Statement_Oct2023.pdf', size: '2.4 MB', uploaded: '2 days ago' },
      { name: 'Director_ID_Proof.jpg', size: '1.1 MB', uploaded: '2 days ago' },
    ],
  },
  {
    id: 2,
    name: 'Global Reach Trading',
    type: 'Wholesaler',
    submitted: 'Oct 23, 2023',
    status: 'Pending',
    idNumber: 'KYC-2023-8941',
    bizType: 'Wholesaler',
    region: 'Europe',
    pan: 'XYZ1234567',
    registration: '9876 5432 1098',
    notes: '',
    files: [],
  },
  {
    id: 3,
    name: 'Nexus Retailers',
    type: 'Customer',
    submitted: 'Oct 22, 2023',
    status: 'Pending',
    idNumber: 'KYC-2023-8940',
    bizType: 'Retailer',
    region: 'Asia',
    pan: 'LMNOP9876',
    registration: '1122 3344 5566',
    notes: '',
    files: [],
  },
];
